import type { Metadata } from "next";
import { Inter, Arizonia, Alex_Brush, Bad_Script, Playball, Great_Vibes, Sacramento } from "next/font/google";
import "./globals.css";

const greatVibes = Great_Vibes({ weight: '400', subsets: ["latin"] });
const sacramento = Sacramento({ weight: '400', subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={greatVibes.className}>{children}</body>
    </html>
  );
}
